### ISSUE TITLE
Update description?

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#144]
A Python module integrating the MediaWiki API and the Wikibase SPARQL endpoint
=> mention wikibase api?

**Comment by LeMyst** [comment]
Updated to "A Python module to interact with the MediaWiki Wikibase API and the Wikibase SPARQL endpoint"

It's better?

**Comment by pangoSE** [comment]
Dunno, isn't mediawiki api one thing and the wikibase api a slap on related to 1 extension of mediawiki (named wikibase?)

**Comment by dpriskorn** [comment]
Dunno, isn't mediawiki api one thing and the wikibase api a slap on related to 1 extension of mediawiki (named wikibase?). Maybe I got it all wrong.

**Comment by LeMyst** [comment]
Both use the same endpoint. When you install the Wikibase Extension, this add some wikibase actions in the MediaWiki API.
