### ISSUE TITLE
core_props fails when prop is an ItemID (bug)

### ISSUE THREAD

**Issue by maximearmstrong** [LeMyst/WikibaseIntegrator#155]
When using `ItemID` property as a core_prop in `ItemEngine`, the [function](https://github.com/LeMyst/WikibaseIntegrator/blob/1393d6f80832dda582760a960d0736842276c544/wikibaseintegrator/wbi_core.py#L721) `__select_item()` fails because of this [line](https://github.com/LeMyst/WikibaseIntegrator/blob/1393d6f80832dda582760a960d0736842276c544/wikibaseintegrator/wbi_core.py#L736), where `get_sparql_value()` returns an `int` for the `self.value` of an `ItemID`, so `replace()` fails.

Is there another way to use an `ItemID` property in a core_props? Or is this a bug? Thanks a lot :)
cc: @annaelleduff

**Comment by LeMyst** [comment]
Hello @maximearmstrong ,
Thank you for your issue.
Do you have an example code that trigger the issue?

**Comment by LeMyst** [comment]
Ok, I can reproduce the issue with 
```python
from wikibaseintegrator import wbi_core
from wikibaseintegrator.wbi_datatype import ItemID

data = ItemID(prop_nr='P1589', value='Q1491734')

item = wbi_core.ItemEngine(debug=True, core_props={'P1589'}, data=data)
print(item.item_id)  # Q2
```

**Comment by LeMyst** [comment]
It's fixed in the master branch.
You can use this one.
I will probably release 0.11.0 at the end of the week.
The 0.12.0 will be a huge rewrite of WBI with a lot of changes. (#152 )

Just for my knowledge, how do you use WikibaseIntegrator?

**Comment by maximearmstrong** [comment]
Thanks a lot @LeMyst ! 
We use WikibaseIntegrator for the [Mobility Database Interface](https://github.com/MobilityData/mobility-database-interface) at MobilityData. We are mostly testing at the moment, but you can access the Mobility Database [here](http://mobilitydatabase.org/wiki/Main_Page), which will be populated soon.
