### ISSUE TITLE
Exponential delay is recommended at WMF when refused because of maxlag 

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#179]
Currently WBI waits more or less the same time between each request:
![bild](https://user-images.githubusercontent.com/68460690/129473832-cfca0876-5710-438d-b5cf-b4b621956b5b.png)

This should instead be 5, 25, 625 seconds to lower the amount of requests to the server by tools during maxlag. (good for the environment too I guess)

**Comment by LeMyst** [comment]
Hello @dpriskorn 
I'm not sure if it's the recommended way to interact with MediaWiki API: https://www.mediawiki.org/wiki/Manual:Maxlag_parameter

WikibaseIntegrator follow the ['error']['lag'] value returned by the API, I'm not sure if it's needed to increase this value.

**Comment by LeMyst** [comment]
Hello @dpriskorn 
Do you have a link to this recommendation?

**Comment by dpriskorn** [comment]
It was suggested here by Multichill to avoid all tools restarting at the same time after maxlag getting below 5. https://phabricator.wikimedia.org/T221774#5679907
It seems to (unfortunately) not be official policy right now.

**Comment by dpriskorn** [comment]
Nikki wrote this in Telegram:
https://www.mediawiki.org/wiki/API:Etiquette already says "When you encounter this error, you may retry that request, however you should increase the time between subsequent requests. A common strategy for this is Exponential backoff."

So it seems to be an official recommendation.

**Comment by LeMyst** [comment]
I don't think we really need to have an exponential wait time.
The current maxlag is already made to delay the scripts, and the increased wait time will allow to mitigate the "all tools restarting at the same time".
Like Nikki wrote, the exponential backoff is a recommended strategy but that is only stated the "we should increase the time between subsequent requests" and the script is compliant with this.
Thank you for the source and the phabricator ticket.
