### ISSUE TITLE
Recommend the user to set a custom user-agent

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#181]
According to this WMF policy https://meta.wikimedia.org/wiki/User-Agent_policy 

> If you run a bot, please send a User-Agent header identifying the bot with an identifier that isn't going to be confused with many other bots, and supplying some way of contacting you (e.g. a userpage on the local wiki, a userpage on a related wiki using interwiki linking syntax, a URI for a relevant external website, or an email address)

`The generic format is <client name>/<version> (<contact information>) <library/framework name>/<version> [<library name>/<version> ...]. Parts that are not applicable can be omitted.` 

I think WBI should mandate a custom user-agent when working towards WMF-endpoints.

**Comment by dpriskorn** [comment]
This can be set to None and then we check for it before any request is sent
https://github.com/LeMyst/WikibaseIntegrator/blob/master/wikibaseintegrator/wbi_config.py#L25

**Comment by LeMyst** [comment]
I'm conflicted on this part.
I'm not really happy to add exception for WMF and the operator should be the one to correctly set a custom user-agent, using functions parameter.
On the other-side, it will be better if WBI can easily differentiate between two scripts (maybe by adding script filename?) and to avoid a site-wide ban.

**Comment by LeMyst** [comment]
Changing the user agent broke the statistics I can have from https://www.wikidata.org/wiki/Special:ApiFeatureUsage

**Comment by dpriskorn** [comment]
I see this has side effects. What about mentioning it in the top of the README instead of mandating it? We could write or link to a good example.

**Comment by dpriskorn** [comment]
> Changing the user agent broke the statistics I can have from https://www.wikidata.org/wiki/Special:ApiFeatureUsage

cannot replicate that. https://www.wikidata.org/wiki/Special:ApiFeatureUsage?wpagent=WikibaseIntegrator&wpstartdate=2021-05-24&wpenddate=2021-08-22 works fine. I tried https://www.wikidata.org/wiki/Special:ApiFeatureUsage?wpagent=WikibaseIntegrator%2F0.10.0+%28https%3A%2F%2Fgithub.com%2FLeMyst%2FWikibaseIntegrator%29&wpstartdate=2021-05-24&wpenddate=2021-08-22 also and compared

**Comment by LeMyst** [comment]
I'll put this change on-hold.
I'm not happy with the changes.
I'll think of a better answer to this issue.
