### ISSUE TITLE
Implement PEP 498

### ISSUE THREAD

**Issue by LeMyst** [LeMyst/WikibaseIntegrator#183]
Used by @dpriskorn in an old commit of #178 
It seem the new way (python 3.6+) to format string in better than the old way of str.format()
More informations in:
- https://realpython.com/python-f-strings/
- https://www.python.org/dev/peps/pep-0498/

Task:
* [ ] Replace all the str.format() to f-string

**Comment by dpriskorn** [comment]
I can help with this if you would like for v.12+ :)
