### ISSUE TITLE
Rewrite WikibaseIntegrator

### ISSUE THREAD

**Issue by LeMyst** [LeMyst/WikibaseIntegrator#184]
Will probably break compatibility 🤷 

### TODO
- [x] Rewrite BaseDataType and Datatypes
- [x] Re-add the __select_item() who search item in SPARQL DB (named get_items/get_item)

### Rewrite FastRunContainer

1. Get data for entity
2. If needed, get data for labels, descriptions and aliases
3. Compare fastrun data from item data
4. Return a boolean if write is required or not, stop on first write required

**Comment by dpriskorn** [comment]
Let's remove the pin now that it is closed.
