### ISSUE TITLE
Avoid long lines in the code

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#191]
Should we set a column limit? 80?

**Comment by LeMyst** [comment]
Hello @dpriskorn 
I already set a column limit for me and it's 180.
I know the "80 characters limit" but it"s really too small for me and, personally, I think it was good 20+ years ago at the era of the terminals but not today with 1080p+ screens.
I may seem selfish, but I will not changes the column limit to something lower than 180.

**Comment by dpriskorn** [comment]
Ok, thanks for the explanation. I never owned a big fancy screen like that :sweat_smile: Oh, wait! I can my PC to my TV to get better resolution :nerd_face:
