### ISSUE TITLE
Raise exception if no summary is provided

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#206]
see https://github.com/LeMyst/WikibaseIntegrator/commit/80fab13df6e8d2380c09199018a7398a9c1d28d7#r55632728

**Comment by LeMyst** [comment]
I don't think overriding the behavior of the API is a good idea.
I don't want to reduce the responsibility of users of WikibaseIntegrator, they should correctly use the library in accordance of the Wikibase instances rules.
If a user want to use the library without adding a summary on his own Wikibase, it's his choice.

**Comment by dpriskorn** [comment]
What about checking if it is a WMF instance and then throw an exception?

**Comment by LeMyst** [comment]
I don't really want to add special case for WMF instances.
I already did it for the User-Agent and I'm not sure if it will not be removed one day 😅

**Comment by dpriskorn** [comment]
Ok, won't fix then.
