### ISSUE TITLE
WBI v0.11 does not append

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#208]
https://www.wikidata.org/w/index.php?title=Lexeme:L33212&diff=1490713824&oldid=1490701719
with code https://github.com/dpriskorn/LexSO/blob/fb1d375665b575ffbc91ee6528d7b2abba2c3c9a/models/wikidata.py#L158

Am I doing something wrong?

**Comment by LeMyst** [comment]
I tried to reproduce the issue on test.wikidata.org but can't.
It's a recurrent issue or only this time?

**Comment by dpriskorn** [comment]
Only once. Afterwards I removed it to avoid losing data.

**Comment by dpriskorn** [comment]
I could readd it and try reproduce if you want?

**Comment by LeMyst** [comment]
Can you try one more time, if you can reproduce the issue on another element, and give me the faulty diff.
Thank you

**Comment by LeMyst** [comment]
Found the issue.
You write "if_exits" instead of "if_exists". A "s" is missing. 😅
