### ISSUE TITLE
Get rid of is_qualifier and is_reference?

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#214]
In LexSO I have a time qualifier now without is_qualifier set at all and it seems to work anyway with 0.11
See https://github.com/dpriskorn/LexSO/blob/master/models/wikidata.py#L132

**Comment by dpriskorn** [comment]
They seem gone from v0.12 so I suggest closing this as fixed :)

**Comment by dpriskorn** [comment]
closing as fixed

**Comment by LeMyst** [comment]
Yeah, I got rid of it in v0.12 but I can't remember why it's needed in v0.11.
