### ISSUE TITLE
frozendict dependency not installed

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#221]
I just installed dev3 and got an error "no module frozendict".
it seems to be in the requirements.txt, so IDK what happened. I installed using pycharm
code here https://github.com/dpriskorn/ItemSubjector

**Comment by LeMyst** [comment]
Fixed in rewrite-wbi, will be ok in dev4. You can install it manually meanwhile.
frozendict was missing in setup.cfg
Updated the GitHub Actions file to correctly use this file.
