### ISSUE TITLE
Can't set snaktype on DataTypes

### ISSUE THREAD

**Issue by pgrond** [LeMyst/WikibaseIntegrator#235]
The `BaseDataType` inhertits from `Claim`. The documentation states that you can add a property `snaktype` to the `BaseDataType`. However, `Claim` does not have a property named `snaktype` and so it throws an error `TypeError: __init__() got an unexpected keyword argument 'snak_type'`

Am I missing something or is this a bug in the rewrite? What should the correct way of working be? If this is a bug, can maybe you can give a direction for your proposed solution, so I might be able to help with a fix.

**Comment by LeMyst** [comment]
Hello @pgrond 
It's more like an outdated docstring in BaseDatatype.
If you want to set the snaktype of a BaseDataType/Claim (I use ExternalID in my example) you can do:
```python
from wikibaseintegrator.datatypes import ExternalID
from wikibaseintegrator.wbi_enums import WikibaseSnakType

externalid = ExternalID()
externalid.mainsnak.snaktype = WikibaseSnakType.NO_VALUE
```

**Comment by LeMyst** [comment]
I'm currently adding typing everywhere (#141) and after this phase I will update the documentation (#209).

**Comment by pgrond** [comment]
Clear, thanks for the explanation.
