### ISSUE TITLE
SPARQL error URLs from WDQS are not output correctly

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#236]
(on dev4)
Since the whole link is not formatted as a link it could confuse the user. They get another error if they click the link than the one caused by the query

![bild](https://user-images.githubusercontent.com/68460690/134764142-d5e6ce3c-f277-47cb-856d-01a7971a886b.png)

compare https://query.wikidata.org/sparql?query=%23Tool%3A+WikibaseIntegrator+wbi_functions.execute_sparql_query%0A%0A++++++++++++SELECT+DISTINCT+%3Fitem+%3FitemLabel+%0A++++++++++++WHERE+%7B%0A++++++++++++++hint%3AQuery+hint%3Aoptimizer+%22None%22.%0A++++++++++++++SERVICE+wikibase%3Amwapi+%7B%0A++++++++++++++++bd%3AserviceParam+wikibase%3Aapi+%22Search%22%3B%0A++++++++++++++++++++++++++++++++wikibase%3Aendpoint+%22www.wikidata.org%22%3B%0A++++++++++++++++++++++++++++++++mwapi%3Asrsearch+%27haswbstatement%3AP31%3DQ13442814+-haswbstatement%3AP921%3DQ29717230+%22Dmel%5CCG5330%22%27+.%0A++++++++++++++++%3Ftitle+wikibase%3AapiOutput+mwapi%3Atitle.+%0A++++++++++++++%7D%0A++++++++++++++BIND%28IRI%28CONCAT%28STR%28wd%3A%29%2C+%3Ftitle%29%29+AS+%3Fitem%29%0A++++++++++++++%3Fitem+rdfs%3Alabel+%3Flabel.%0A++++++++++++++%23+We+lowercase+and+remove+common+symbols%0A++++++++++++++%23+This+has+to+match+the+function+in+cleaning.py%0A++++++++++++++BIND%28REPLACE%28LCASE%28%3Flabel%29%2C+%22%2C%22%2C+%22%22%29+as+%3Flabel1%29%0A++++++++++++++BIND%28REPLACE%28%3Flabel1%2C+%22%3A%22%2C+%22%22%29+as+%3Flabel2%29%0A++++++++++++++BIND%28REPLACE%28%3Flabel2%2C+%22%3B%22%2C+%22%22%29+as+%3Flabel3%29++++++++++%0A++++++++++++++BIND%28REPLACE%28%3Flabel3%2C+%22%5C%5C%28%22%2C+%22%22%29+as+%3Flabel4%29%0A++++++++++++++BIND%28REPLACE%28%3Flabel4%2C+%22%5C%5C%29%22%2C+%22%22%29+as+%3Flabel5%29%0A++++++++++++++BIND%28REPLACE%28%3Flabel5%2C+%22%5C%5C%5B%22%2C+%22%22%29+as+%3Flabel6%29%0A++++++++++++++BIND%28REPLACE%28%3Flabel6%2C+%22%5C%5C%5D%22%2C+%22%22%29+as+%3Flabel7%29%0A++++++++++++++BIND%28REPLACE%28%3Flabel7%2C+%22%5C%5C%5C%5C%22%2C+%22%22%29+as+%3Flabel8%29%0A++++++++++++++BIND%28%3Flabel8+as+%3Fcleaned_label%29%0A++++++++++++++%23+We+try+matching+beginning%2C+middle+and+end%0A++++++++++++++FILTER%28CONTAINS%28%3Fcleaned_label%2C+%22+dmel%5Ccg5330+%22%40en%29+%7C%7C+%0A+++++++++++++++++++++REGEX%28%3Fcleaned_label%2C+%22.%2A+dmel%5Ccg5330%24%22%40en%29+%7C%7C%0A+++++++++++++++++++++REGEX%28%3Fcleaned_label%2C+%22%5Edmel%5Ccg5330+.%2A%22%40en%29%29%0A++++++++++++++%23+remove+more+specific+forms+of+the+main+subject+also%0A++++++++++++++%23+Thanks+to+Jan+Ainali+for+this+improvement+%3A%29%0A++++++++++++++MINUS+%7B%3Fitem+wdt%3AP921+%3Ftopic.+%3Ftopic+wdt%3AP279+wd%3AQ29717230.+%7D%0A++++++++++++++SERVICE+wikibase%3Alabel+%7B+bd%3AserviceParam+wikibase%3Alanguage+%22en%22.+%7D%0A++++++++++++%7D%0A++++++++++++&format=json with https://query.wikidata.org/sparql?query=%23Tool%3A+WikibaseIntegrator+wbi_functions.execute_sparql_query%0A

**Comment by LeMyst** [comment]
I think the issue is from your IDE who only "linkify" before the first new line.
I don't think I've control on that.

**Comment by dpriskorn** [comment]
Oh, ok, I'll see if I can reproduce in the terminal and reopen in that case.
