### ISSUE TITLE
core_props with datatype URL do not work

### ISSUE THREAD

**Issue by razz0** [LeMyst/WikibaseIntegrator#266]
The properties given in `core_props` with datatype URL do not seem to work. The SPARQL queries created for checking if a property and value pair exists are not correctly formatted for that datatype. The Wikibase SPARQL endpoint exposes these values as Literal `"http://example.com/"` and WikibaseIntegrator attempts to query the values as `"<http://example.com/>"`.

Tested with Wikibase 1.35 and WikibaseIntegrator 0.11.1.

**Comment by LeMyst** [comment]
Hello @razz0 
Thank you for your issue.
Do you have some code to check this?

**Comment by LeMyst** [comment]
I tried to reproduce your issue without success on Wikidata.

Are you sure your property is declared as the type "URL" in your Wikibase (and it's not a String or something else)?

My query on Wikidata (generated from WikibaseIntegrator v0.11):
https://query.wikidata.org/#SELECT%20%2a%20WHERE%20%7B%0A%20%20%3Fitem_id%20p%3AP856%20%3Fs.%0A%20%20%3Fs%20ps%3AP856%20%3Chttp%3A%2F%2Fwww.lyon.fr%2F%3E.%0A%7D

**Comment by razz0** [comment]
Thanks for looking into this.

Indeed, I should have double checked the datatype I used, as it is not URL, but External identifier. Apologies for this. I have mistakenly used the `wbi_datatype.Url` for the External identifier datatype, which seems to be the cause of the problem. The stored values are HTTP URIs, so as such the corresponding property could use datatype URL. 

There is nothing that needs fixing and I'll close this issue. I would however suggest to add some type checking to prevent this kind of issues. Thanks again for helping to sort this out!
