### ISSUE TITLE
Give an example for this language setting

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#270]
https://github.com/LeMyst/WikibaseIntegrator/blob/32698a69d10d1cf50b18961d3fabc36111128883/wikibaseintegrator/wbi_helpers.py#L325
e.g. "This is a Wikimedia Language Code e.g. "en" for English see a list of all codes here: url

**Comment by LeMyst** [comment]
Improved in 27d88afc883b888b40e8119560cd147a86f54465
It's good enough?

**Comment by LeMyst** [comment]
Add the WMF language code list for Wikidata
