### ISSUE TITLE
Give an example value

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#271]
https://github.com/LeMyst/WikibaseIntegrator/blob/32698a69d10d1cf50b18961d3fabc36111128883/wikibaseintegrator/wbi_helpers.py#L325
This accepts True or False and defaults to x

**Comment by LeMyst** [comment]
Hello @dpriskorn 
Are you sure you quoted the right line? It's the same in #270

**Comment by dpriskorn** [comment]
no, not sure. github bug perhaps. anyway it is in the new search entities function
