### ISSUE TITLE
RC1: Document return from item.write()

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#279]
Hi 
Earlier version returned either an entity id or an error if I remember correctly.

I liked that because it makes it easy to find out which QID you just created.

![bild](https://user-images.githubusercontent.com/68460690/151672860-cba35a5a-9b36-4eab-b52d-c1ad60aaeae5.png)

![bild](https://user-images.githubusercontent.com/68460690/151672855-df1209c3-19d7-42ea-8931-e6065dd4edbb.png)

![bild](https://user-images.githubusercontent.com/68460690/151672851-198f4543-6a24-418b-bf92-94103dd9c548.png)

Since we now get the full Item I guess this is an improvement :)

I use this code to write and check the result. Does it throw an exception if something goes wrong? I would like that documented in the item.write() docstring and perhaps in README/documentation.
```
            result = item.write(
                summary=(f"Added main subject [[{match.qid}|{match.label}]] " +
                         f"with [[Wikidata:Tools/asseeibot]] v{config.version}")
            )
            if isinstance(result, Item):
                console.print(f"[green]Uploaded '{match.label}' to[/green] {match.qid.url()}")
            else:
                raise ValueError("Did not get an item back from WBI, something went wrong :/")
```

**Comment by LeMyst** [comment]
You can easily retrieve the newly created entity ID with `result.id`

Do you have the stacktrace with the Exception?

**Comment by dpriskorn** [comment]
> Do you have the stacktrace with the Exception?

Which exception?

**Comment by LeMyst** [comment]
> > Do you have the stacktrace with the Exception?
> 
> Which exception?

I misread your original message.

Yes, if the API returns an error, an MWApiError exception is raised.

I will update the docstring.
