### ISSUE TITLE
RC1: Anonymous exception thown after logging in if a certain time has passed

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#283]
![bild](https://user-images.githubusercontent.com/68460690/152593515-66fa2a86-8a9d-49b6-8b71-b9dc9f5bd2a0.png)
I run my tools on Toolforge using screen. The process can run for days. Sometimes I get this error because the login has timed out on WMFs side I guess.
Could we try logging in before throwing an exception?
Or should I do it in the tool?

**Comment by dpriskorn** [comment]
> I got this issue on my Wikibase instance multiple times, but that was before v0.12.
> 
> I didn't work on big corpus recently, that is probably why I didn't got it since.
> 
> It's an issue difficult to reproduce :(

Really? I assume it can be reproduced by something as simple as

Log in with wbi
Sleep for 24 hours or as long needed to the login to expire 
Add a claim and write

**Comment by LeMyst** [comment]
The issue seems to be https://www.mediawiki.org/wiki/Manual:$wgObjectCacheSessionExpiry
After one hour, the session cookie is not valid anymore.

I don't know how to manage this (without reauthentification)

**Comment by LeMyst** [comment]
Partial fix in [v0.12.0rc2](https://github.com/LeMyst/WikibaseIntegrator/releases/tag/v0.12.0rc2)
