### ISSUE TITLE
Item (BaseDataType) and Item (BaseEntity) are confusing

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#285]
I think we should rename one of them or both, so they don't confuse the users.
Wikidatas datamodel is complex, so let's make it simple to understand what the classes are representing by just looking at the name.

**Comment by LeMyst** [comment]
Same for Property and Lexeme 😞

**Comment by dpriskorn** [comment]
I have a suggestion, let's call them 
PropertyEntity, LexemeEntity, etc.
PropertyBaseDataType, LexemeBaseDataType, etc
It's not pretty, and they are longer, but we get less confusion

Alternatively, we keep the names and set a best practice and do this in the documentation:
from wikibaseintegrator.entities import Item as ItemEntity
....

and
from wikibaseintegrator.datatypes import Item as ItemDT
....

**Comment by LeMyst** [comment]
Thanks you for your suggestions

Alternatively, you have this also:
from wikibaseintegrator import datatypes
from wikibaseintegrator import entities

claim = datatypes.Item(value='test')
item = entities.Item(...)

**Comment by dpriskorn** [comment]
I like that better. 😀

**Comment by LeMyst** [comment]
I added the suffix "Entity" to Entity classes, like ItemEntity, PropertyEntity, etc.
