### ISSUE TITLE
v0.12: Attributes are missing from the classes

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#286]
E.g. BaseEntity does not have a "value" attribute.
This makes it hard to make a class diagram because I have to look through all methods of all child classes to find attributes 😅
If we add pydantic to the BaseEntity and BaseDataType it will help by complaining every time an attribute is missing 😀

**Comment by LeMyst** [comment]
Do you mean BaseDataType instead of BaseEntity? Because I don't see why BaseEntity should have a value. 🤔

**Comment by dpriskorn** [comment]
Yes. Bit BaseDataType inherits from Claim so it is missing there in that case.

**Comment by LeMyst** [comment]
There is no "value" attribute in BaseDataType (or BaseEntity), so I'm a little lost on what you talk about.
I tried to implement pydantic in the current code without success 😔

**Comment by dpriskorn** [comment]
> There is no "value" attribute in BaseDataType (or BaseEntity), so I'm a little lost on what you talk about. I tried to implement pydantic in the current code without success 😔

Me too, I ran into a weird error. I'll document it in the pydantic issue

**Comment by dpriskorn** [comment]
https://github.com/dpriskorn/WikibaseIntegrator/tree/pydantic-test here are a few improved classes
![bild](https://user-images.githubusercontent.com/68460690/153579871-935ad0be-5500-4104-bb5c-15563e05d963.png)

**Comment by LeMyst** [comment]
I've added getter and setter in BaseEntity
