### ISSUE TITLE
RC1: WBI does not check if the propnr is None

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#288]
This leads to a confusing API error
![bild](https://user-images.githubusercontent.com/68460690/153728018-5c80efaf-c39c-4eb8-8019-58ad98d92194.png)
![bild](https://user-images.githubusercontent.com/68460690/153728032-f9945610-442c-44a1-813c-05aaf81cd153.png)

**Comment by LeMyst** [comment]
Do you have the item QID?

**Comment by dpriskorn** [comment]
> Do you have the item QID?

No, the output with None happened when I forgot to add proper argument to one of the subclasses of basetype and called item.add_claims() and then item.get_json()
IMO WBI should check if it got a a propnr and value/time at instantiating

**Comment by dpriskorn** [comment]
I'll close this as fixed. We can always reopen if necessary.
