### ISSUE TITLE
RC1: Content-Type is missing according to the API

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#289]
https://github.com/LeMyst/WikibaseIntegrator/blob/81ce197ae2c63dea9ec645a853cd3beaa2dcac24/wikibaseintegrator/wbi_helpers.py#L160
![bild](https://user-images.githubusercontent.com/68460690/153729276-6a321cc7-37b9-412b-9da7-d43276e30923.png)

**Comment by LeMyst** [comment]
MediaWiki documentation is not really clear on this part. (https://www.mediawiki.org/wiki/API:Edit)
But I'll add a default "Content-Type: application/json"

**Comment by LeMyst** [comment]
There is an issue in your code.
mediawiki_api_call_helper() was made to support "data" queries.

You have two ways to do what you want:
```
params = {
    'action': 'query',
    'list': 'search',
    'srprop': '',
    'srlimit': '1',
    'srsearch': doi
}

mediawiki_api_call_helper(data=params, allow_anonymous=True)
```
or
```
mediawiki_api_call(method='GET', mediawiki_api_url=f'http://www.wikidata.org/w/api.php?format=json&action=query&list=search&srprop=&srlimit=1&srsearch={doi}', allow_anonymous=True)
```

The first one is recommended

**Comment by dpriskorn** [comment]
Thanks. Could this be explained in the doc string? Or maybe I overlooked it?
