### ISSUE TITLE
RC1: Bare ValueError not helpful for users

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#290]
![bild](https://user-images.githubusercontent.com/68460690/154008749-471c98c3-bdd5-4109-a95f-20bfa6673b94.png)
It means that the reference was not recognized as a (subtype of) claim
see https://github.com/LeMyst/WikibaseIntegrator/blob/11c4b39a0ee3b034feff95ce43562a0012795ad3/wikibaseintegrator/models/claims.py#L157

It turned out to be None
![bild](https://user-images.githubusercontent.com/68460690/154011955-71af573f-db68-41f6-92b4-a1f77336579e.png)

**Comment by LeMyst** [comment]
Changes pushed to rewrite-wbi
