### ISSUE TITLE
RC1: IndexError: list assignment index out of range when comparing qualifiers with multiple Snaks

### ISSUE THREAD

**Issue by pgrond** [LeMyst/WikibaseIntegrator#295]
When comparing qualifiers I get an IndexError: list assignment index out of range. 

I think this is because my qualifiers are multilingual, so they consist of multiple Snaks in a qualifier.

`len(self_qualifiers)` returns 1, but `enumerate(self_qualifiers)` loops over the Snaks in the qualifier, which causes an error because the `flg` list is constructed based on the `len`: `flg = [False for _ in range(len(self_qualifiers))]`

**Comment by dpriskorn** [comment]
Could you link to the offending line in the source?

**Comment by pgrond** [comment]
https://github.com/LeMyst/WikibaseIntegrator/blob/8467f3121c4e4ebc36b1df2b64af51d77c229fba/wikibaseintegrator/models/claims.py#L284

**Comment by LeMyst** [comment]
Solved in e5c32366f26f7f100066c293a278f610f943c49d

I'll release a new v0.12 package this week.
