### ISSUE TITLE
Support clearing all claims

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#315]
As a user I would like to remove all claims from an item that already exists in the Wikibase

Would it be an idea to have a public method in item so we can do something like item.clear_claims()?

**Comment by dpriskorn** [comment]
The method would just do self.claims = Claims()

**Comment by LeMyst** [comment]
Doc and function updated in commit 66e79918c8d54b7d95857e7ef42613e990afa190
