### ISSUE TITLE
Example for qualifier setting - is this implemented yet?

### ISSUE THREAD

**Issue by WolfgangFahl** [LeMyst/WikibaseIntegrator#323]
In https://github.com/WolfgangFahl/pyOnlineSpreadSheetEditing/blob/main/wd/gsimport.py i am successfully using wikibaseintegrator to read data from a google spreadsheet including the mapping information and then interactively add the data row by row to wikidata. 
An input e.g. might be https://docs.google.com/spreadsheets/d/1-6llZSTVxNrYH4HJ0DotMjVu9cTHv2WnT_thfQ-3q14 

and the results would show up in https://scholia.toolforge.org/event-series/Q111739322

The events would need a qualifier e.g. https://www.wikidata.org/wiki/Q111739923 is the 92nd installement of the series. so  https://www.wikidata.org/wiki/Property:P179 (part of the series) needs to be qualified with https://www.wikidata.org/wiki/Property:P1545 (series ordinal). 

**How are qualifiers to be set with WikibaseIntegegrator?**

**Comment by WolfgangFahl** [comment]
see also https://github.com/SuLab/WikidataIntegrator/issues/193

**Comment by WolfgangFahl** [comment]
https://github.com/LeMyst/WikibaseIntegrator/blob/461ef958f94e18c74122ee276e8e183d16a816e1/wikibaseintegrator/wbi_datatype.py#L83 does the actual setting of qualifiers. This is forced to be at construction time at this time so qualifiers need to be known at construction time. I think this should be refactored to allow to add qualifiers after construction.

**Comment by LeMyst** [comment]
Hello @WolfgangFahl ,
Firstly, I recommend you to use the dev version of WikibaseIntegrator (v0.12.0) who have some breaking changes.
But if you want to use qualifiers with v0.11.x you can do as follow:
```python
from wikibaseintegrator import wbi_datatype, wbi_core

# Create the qualifier
qualifiers = wbi_datatype.String(value='92', prop_nr='P1545', is_qualifier=True)

# Create the statement
data = [wbi_datatype.ItemID("Q111739322", "P179", qualifiers=qualifiers)]

# Update the item
wd_item = wbi_core.ItemEngine(item_id='Q111739923', data=data)

# Write to the WB instance
wd_item.write(login=None)
```
Should do something like this:
* Update the item Q111739923
* Add a statement P179 with a value of Q111739322
* This statement have a qualifier P1545 with a value of 92
(if I correctly understood what you want, I'm not sure of my code, I didn't use the v0.11 anymore)

And to do the same thing with v0.12.0:
```python
from wikibaseintegrator import WikibaseIntegrator
from wikibaseintegrator.datatypes import String, Item
from wikibaseintegrator.models import Qualifiers

wbi = WikibaseIntegrator()

# Get the current item
wb_item = wbi.item.get(entity_id='Q111739923')

# Create the qualifier
qualifiers = Qualifiers()
qualifiers.add(String(value='92', prop_nr='P1545'))

# Add/Update the item with the statement
wb_item.claims.add(claims=Item(value='Q111739322', prop_nr='P179', qualifiers=qualifiers))

# Write to the WB instance
wb_item.write()
```

v0.12.0 is more object oriented, and after loading the item with the function get(), you can access claims and theirs qualifiers/references.

I hope I was clear enough.

**Comment by dpriskorn** [comment]
I suggest closing this.

**Comment by WolfgangFahl** [comment]
@dpriskorn  indeed my question is answers. My comments might lead to another issue
