### ISSUE TITLE
KeyError: 'title'

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#325]
![bild](https://user-images.githubusercontent.com/68460690/166231005-3ba87cd8-2dfc-4e1b-a50b-9830d71a47b7.png)
code here https://github.com/internetarchive/wcdimportbot/commit/84be651e1eef8af1e803b5d234cb5c8de45313ac
WBI commit used: 04a6f4c148ba8e6e47e51a01b61d34b845ff88ba

**Comment by LeMyst** [comment]
Hello @dpriskorn 
Thank you for your issue and your PR.

Can I have more informations about your environment? What's your version of Mediawiki?

Thank you,

**Comment by dpriskorn** [comment]
It's the version in opencura/wbstack. See https://wikicitations.wiki.opencura.com/wiki/Special:Version

**Comment by LeMyst** [comment]
Thank you.
Really need the unit tests against multiple versions of MediaWiki 😔
