### ISSUE TITLE
Shouldn't this return Optional[ItemEntity] 

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#329]
https://github.com/LeMyst/WikibaseIntegrator/blob/189b102bfa33ed66bea26e0de50674c062410542/wikibaseintegrator/entities/item.py#L40
What if the Q-item has been deleted? None seems like a good response then, IMO. WDYT?

**Comment by LeMyst** [comment]
If the Q-entity is non existant, the function return a MWApiError (Could not find an entity with the ID ...)

I prefer this approach to avoid the user thinking that the entity has been correctly loaded, and to give more informations than a simple "empty" item.

**Comment by dpriskorn** [comment]
Unfortunately the MWApiError  is ambiguous and not good to hardcode downstream IMO. I would prefer a clear exception in that case e.g. NonExistantItemError or something like that.

**Comment by LeMyst** [comment]
Fixed in #331
