### ISSUE TITLE
v.0.12 WBI does not enforce limit on label to Wikibase limit of 250 chars maximum

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#342]
![bild](https://user-images.githubusercontent.com/68460690/171554915-d76237cd-f1a6-4df0-9b00-caca68ea58f9.png)

**Comment by LeMyst** [comment]
I'll not enforce a limit inside WBI because any Wikibase instance can be different.
But a more specific error handling can help the user

**Comment by dpriskorn** [comment]
Same for description being max 400 chars
![bild](https://user-images.githubusercontent.com/68460690/171868292-797824d7-0097-4d6a-9659-e93828798968.png)

**Comment by LeMyst** [comment]
I will not set theses values inside WikibaseIntegrator because they can changes between versions of Wikibase or configuration of Wikibase instances.
