### ISSUE TITLE
v0.12 WBI cannot handle the "Item:"-prefixed QIDs from a WBI method

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#343]
![bild](https://user-images.githubusercontent.com/68460690/171559931-dcbda8de-6fd5-4928-8700-971c7c48a040.png)
See https://github.com/LeMyst/WikibaseIntegrator/blob/549008eebdb5e7bfd4d4d07a3704c86870902eef/wikibaseintegrator/wbi_exceptions.py#L27
I suggest that the method either remove the prefix or that item.py is changed to handle it correctly.

**Comment by LeMyst** [comment]
Fixed
