### ISSUE TITLE
Use an enum for all datatypes of properties instead of a string

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#349]
This lowers the risk of errors for users trying to create properties.
https://github.com/LeMyst/WikibaseIntegrator/blob/291f14f0379d77e10257edccab689a40c1f0405f/wikibaseintegrator/entities/property.py#L16
I can work on this if you would like :)

**Comment by dpriskorn** [comment]
I can work on this if you would like :)

**Comment by LeMyst** [comment]
I've not tested it.
It's OK for you: 1708586ef85aa1fb5511ab97756ba7c7316ddfad ?

**Comment by dpriskorn** [comment]
This looks better :) https://github.com/LeMyst/WikibaseIntegrator/commit/20a5f856170c33ba3777811c493a082ea624688b
I'm closing since you fixed it 🚀 🤩
