### ISSUE TITLE
v0.12 WBI does not warn when adding a LanguageValue directly to labels= or descriptions=

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#350]
![bild](https://user-images.githubusercontent.com/68460690/173252289-35cc4220-50e7-40f6-a87f-1bfb95941889.png)
code used is here: https://github.com/internetarchive/wcdimportbot/pull/42/commits/23d1afd32eff1a59a85c7552d4e63b82b88d1344
note I'm not using vanilla WBI, but a slightly dated fork with one commit, see https://github.com/dpriskorn/WikibaseIntegrator/tree/patch-7 (the change has already been submitted here https://github.com/LeMyst/WikibaseIntegrator/pull/341)

**Comment by LeMyst** [comment]
Hello @dpriskorn ,

Sorry for the lack of response, lot of things to do beside WBI.
I'll properly test property creation tomorrow and check if everything work correctly.
Can you give the version of Wikibase/Mediawiki you use?

**Comment by dpriskorn** [comment]
Here is the version information: https://sandbox.wiki/wiki/Special:Version <html><body>


MediaWiki | 1.36.3
-- | --



</body>
</html>[MediaWiki](https://www.mediawiki.org/) 	1.36.3

**Comment by LeMyst** [comment]
I've created a PR on your repo
https://github.com/internetarchive/wcdimportbot/pull/43

**Comment by dpriskorn** [comment]
Thanks, it now seems to work. I would have liked WBI to complain about my incorrect invocation :)

**Comment by LeMyst** [comment]
Add warning in 7ed6cd91044dfb36aee6eb6e95c2317c2c3a7f00
