### ISSUE TITLE
Wrong return type for qualifiers.get()

### ISSUE THREAD

**Issue by pgrond** [LeMyst/WikibaseIntegrator#354]
https://github.com/LeMyst/WikibaseIntegrator/blob/9cc5523577beadec73e1cf594514a5d7d93f976e/wikibaseintegrator/models/qualifiers.py#L37

This method has a return type of Snak, but the qualifiers are set in a list https://github.com/LeMyst/WikibaseIntegrator/blob/9cc5523577beadec73e1cf594514a5d7d93f976e/wikibaseintegrator/models/qualifiers.py#L52
 
So `.get()` should return a list.

**Comment by LeMyst** [comment]
Fixed in https://github.com/LeMyst/WikibaseIntegrator/pull/152/commits/02f764705342d52b353417b7fd2af89e4d8c0d49

Thank you
