### ISSUE TITLE
Remove IDE-specific files from the repository

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#360]
I suggest removing .idea/

**Comment by LeMyst** [comment]
At the beginning of the project, I didn't really want to upload the .idea folder, but my goal was the share the project settings so people can easily start using the project and easily follow the IDE rules, like code styles.

I understand not everyone use or want to use JetBrains PyCharm, but I don't force anybody, and if they want to use it, it's easier for them.
The folder is not packaged inside the release.

**Comment by dpriskorn** [comment]
I use the same IDE and it suggested I commit the changes it made to the idea files. I'm unsure how that would affect the project so I ignored them. 
I don't think it helps new contributors at all 🤷‍♂️

I prefer keeping the repo clean so I only commit stuff of value and not accidentally some other file.
