### ISSUE TITLE
Don't replace if claim is the same

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#366]
Hi I found
https://github.com/LeMyst/WikibaseIntegrator/blob/d5c8a754a103592843d9d549d623c4fa875f906b/wikibaseintegrator/models/claims.py#L58

Would it add anything of value if we md5hash all claims and compare the hashes to know whether they are the same or not?

**Comment by LeMyst** [comment]
I thin the __eq__() can already do most of the work by comparing object.
