### ISSUE TITLE
v0.12.0: remove claims has no effect

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#376]
Am I doing something wrong?
I don't really understand the remove logic. It should be documented so that it is easy to follow the logic and find bugs.
![bild](https://user-images.githubusercontent.com/68460690/179735187-7d50a9a7-40ce-44a0-ab7e-6523c4458128.png)

**Comment by LeMyst** [comment]
It's because, for an existing property on a wikibase instance, you can't simply remove the claims from the entity.
You need to mark this claims as "removed" and write the information to the the instance
You can test if the claim is non-existent or have the flag "removed" as true.
