### ISSUE TITLE
v0.12.0: REPLACE_ALL does not work as expected

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#379]
I'm trying to update an item in Wikibase
The item has a website = Q161 statement.
I remove all website statements and add the new ones using ActionIfExists.REPLACE_ALL but the old statements do not get deleted and remain on the item.
See code here: https://github.com/internetarchive/wcdimportbot/blob/9404e0d93247aa5c321ee3772c2d5b590d023f3c/src/models/wikibase/crud/update.py#L88
[Here the effect is visible](https://sandbox.wiki/wiki/Item:Q2635). There should only be 1 website claim (to the google.com item) but there are 3.
![bild](https://user-images.githubusercontent.com/68460690/179763415-ac5eaada-aa09-43d4-8223-a998441b0d15.png)
The WBI used is my fork which actually removes the claims, see https://github.com/LeMyst/WikibaseIntegrator/pull/378

**Comment by dpriskorn** [comment]
Could this be because I have botched a correctly working remove() method because I did not understand the inner workings?

**Comment by LeMyst** [comment]
Hello @dpriskorn 
I quicky tried the "replace_all" on my local wikibase without finding any issues.
```
item = wbi.item.get(1)
new_claim = Item(prop_nr='P3', value='Q1')
item.claims.add(new_claim)
item.claims.add(new_claim)
item.claims.add(new_claim)
item.write()
```

Can you share the construction of your entity, before the write ?

**Comment by dpriskorn** [comment]
That does not seem to cover the issue. 🤷‍♂️
My issue is: I have an item with P1->Q1 and P1->Q3 in a Wikibase   Now I want to replace them with only P1->Q4. 
That seems impossible using v0.12.0. The first two are not removed. It does not help to mark them removed either.

**Comment by LeMyst** [comment]
My current test:
```
item = wbi.item.get(1)
item.claims.add([Item(prop_nr='P3', value='Q1'), Item(prop_nr='P3', value='Q2')])
item.write()
```

![image](https://user-images.githubusercontent.com/1592048/181016470-04c5977c-be3b-424d-99fa-831ce6d95fd3.png)

then:

```
item = wbi.item.get(1)
item.claims.add([Item(prop_nr='P3', value='Q4')])
item.write()
```

![image](https://user-images.githubusercontent.com/1592048/181016569-edbbe156-355c-4c1c-b6e2-41bd773bc6c6.png)

**Comment by dpriskorn** [comment]
Thanks for sharing this. I conclude that the bug must be in my code somewhere.

**Comment by dpriskorn** [comment]
> My current test:
> 
> ```
> item = wbi.item.get(1)
> item.claims.add([Item(prop_nr='P3', value='Q1'), Item(prop_nr='P3', value='Q2')])
> item.write()
> ```
> 
> ![image](https://user-images.githubusercontent.com/1592048/181016470-04c5977c-be3b-424d-99fa-831ce6d95fd3.png)
> 
> then:
> 
> ```
> item = wbi.item.get(1)
> item.claims.add([Item(prop_nr='P3', value='Q4')])
> item.write()
> ```
> 
> ![image](https://user-images.githubusercontent.com/1592048/181016569-edbbe156-355c-4c1c-b6e2-41bd773bc6c6.png)

How do you tell WBI to REPLACE_ALL? I don't see that in this post at all. Is it the default behavior?

**Comment by dpriskorn** [comment]
Oh, indeed it is I see now. 
![bild](https://user-images.githubusercontent.com/68460690/181795954-4d2c0040-f243-43d0-a5f7-1e584512965c.png)
