### ISSUE TITLE
Document helper for todays time

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#422]
Often when working with references I need to state a statement was based on a specific data. Very often today. 
See GPLv3 code here
https://github.com/dpriskorn/hiking_trail_matcher/blob/support_multiple_languages/src/wikidata_time_format.py

**Comment by LeMyst** [comment]
Hello @dpriskorn ,

Did you try `Time(time='now')` ?

(Yes, another lack of documentation 😞 )

**Comment by dpriskorn** [comment]
No, thanks for the tip!

**Comment by dpriskorn** [comment]
renamed

**Comment by dpriskorn** [comment]
Wohoo 🥳
