### ISSUE TITLE
Error adding WBI via Poetry

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#428]
[Here is the example project I cloned](https://github.com/GregaVrbancic/fastapi-celery)
![bild](https://user-images.githubusercontent.com/68460690/193066269-096399f7-bd28-4ad9-b3cd-38cd78cff3c5.png)

**Comment by LeMyst** [comment]
Hello @dpriskorn ,

I think you can solve this by limiting your required python version to 3.11 and less.

**Comment by dpriskorn** [comment]
Thanks for the tip 🤩
This solved the issue
![bild](https://user-images.githubusercontent.com/68460690/193088333-e51946b6-f944-493c-89de-12c34e1474e0.png)
