### ISSUE TITLE
No module named pkg_resources

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#429]
https://github.com/LeMyst/WikibaseIntegrator/search?q=pkg_resources
![bild](https://user-images.githubusercontent.com/68460690/193402649-45907407-68c7-437d-80fb-9d6c2191c65e.png)
![bild](https://user-images.githubusercontent.com/68460690/193402579-ab5f2d53-4003-44fc-b8d1-c347721907b8.png)
![bild](https://user-images.githubusercontent.com/68460690/193402583-82d94697-3449-4465-8b98-5b2beb4d8f24.png)
see the code here https://github.com/dpriskorn/ItemSubjector/pull/63/commits/0add4cf7455076c94810dfe44a57b4772f63a47e
this points to that the setuptools dependency should be added?
![bild](https://user-images.githubusercontent.com/68460690/193402700-a64e85d4-eda2-41eb-ba57-37e5ce23af49.png)

**Comment by LeMyst** [comment]
Can you try to install the package `setuptools` with `pip install setuptools` ?

**Comment by LeMyst** [comment]
I've removed the pkg_resources dependency in #430

**Comment by dpriskorn** [comment]
> Can you try to install the package `setuptools` with `pip install setuptools` ?
> 
> 

Yes and it fixed the problem
