### ISSUE TITLE
Can't write item with claims

### ISSUE THREAD

**Issue by LizzAlice** [LeMyst/WikibaseIntegrator#433]
I have a problem when writing an item that I've added claims to into my private wikibase. If I don't add any claims, but other things like aliases etc, everything works. But if I try adding claims, I get `wikibaseintegrator.wbi_exceptions.ModificationFailed: 'Unexpected entity type item'`. I thought that I had followed the tutorial in the README, but apparently, something is missing.

`entity = self.wikibase_integrator.item.get(entity_id=internal_id)`

`claims = []`

`claims.append( Item( value="Q13485782", prop_nr="P3",) )`
`entity.claims.add(claims,ActionIfExists.APPEND_OR_REPLACE, )`
`entity.write(login=test_login)`

**Comment by LeMyst** [comment]
Hello @LizzAlice 
Can you confirm me your property "P3" it's an "Item" type, otherwise, what's the type of this property ?

**Comment by LizzAlice** [comment]
P3 is a property, corresponding to _subclass of_  in wikidata, but without the claims (only labels, descriptions, aliases).

**Comment by dpriskorn** [comment]
Please share a screenshot of the property where the type is visible

**Comment by LeMyst** [comment]
Can you open the page:
https://<YOUR WIKIBASE URL>/w/api.php?action=wbgetentities&ids=P3&props=info

and copy paste the info here.

An exemple from wikidata can be seen here:
https://www.wikidata.org/w/api.php?action=wbgetentities&ids=P17&props=info

**Comment by LizzAlice** [comment]
{
    "entities": {
        "P3": {
            "pageid": 4,
            "ns": 122,
            "title": "Property:P3",
            "lastrevid": 4,
            "modified": "2022-09-20T10:06:33Z",
            "type": "property",
            "datatype": "wikibase-property",
            "id": "P3"
        }
    },
    "success": 1
}

**Comment by dpriskorn** [comment]
> {
> 
>     "entities": {
> 
>         "P3": {
> 
>             "pageid": 4,
> 
>             "ns": 122,
> 
>             "title": "Property:P3",
> 
>             "lastrevid": 4,
> 
>             "modified": "2022-09-20T10:06:33Z",
> 
>             "type": "property",
> 
>             "datatype": "wikibase-property",
> 
>             "id": "P3"
> 
>         }
> 
>     },
> 
>     "success": 1
> 
> }

That property only accept other properties. It should be "wikibase-item" like the P17 example url @LeMyst sent above.

**Comment by LizzAlice** [comment]
Oh, so I misunderstood the use of "datatype". So the datatype describes the content, not the property/item itself? If the property did not reference an item, but a String, would the datatype be String?

**Comment by LeMyst** [comment]
> Oh, so I misunderstood the use of "datatype". So the datatype describes the content, not the property/item itself? If the property did not reference an item, but a String, would the datatype be String?

Yes, you have more informations about Datatypes, with examples, here: https://www.wikidata.org/wiki/Help:Data_type
