### ISSUE TITLE
suboptimal construction of MWApiError

### ISSUE THREAD

**Issue by cknoll** [LeMyst/WikibaseIntegrator#449]
During experimenting with my own wikibase instance I often provoke a an ` MWApiError` in the following line:

https://github.com/LeMyst/WikibaseIntegrator/blob/9dd9663f1a4d7164d890f4cc7fbe9528e9fff1b0/wikibaseintegrator/wbi_helpers.py#L125

For easier debugging it would be nice to wrap my call e.g. to `item.write()` with a `try ... except` clause that prints the content of the `json_data`.

However, after the exception has occurred I cannot access this dict for the following reason: Inside ` MWApiError.__init__`  the `json_data` is not stored as an attribute to self (as I would suggest) but instead just evaluated, see https://github.com/LeMyst/WikibaseIntegrator/blob/9dd9663f1a4d7164d890f4cc7fbe9528e9fff1b0/wikibaseintegrator/wbi_exceptions.py#L43

Additionally, I think that this dict is not (always) accessed correctly as in one specific error case I got the following `json_dict`

```
{'error': {'code': 'not-recognized-language',
  'info': 'The supplied language code was not recognized.',
  'messages': [{'name': 'wikibase-api-not-recognized-language',
    'parameters': [],
    'html': {'*': 'The supplied language code was not recognized.'}}],
  '*': 'See https://fedidata.wikibase.cloud/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes.'}}
```
This means: the keys `info` and `messages`  are not on the top level of the dict but instead part of the `errors` subdict.

**Comment by LeMyst** [comment]
I've created the PR #450 

For the first point, I've added a attribute to MWApiError to easily access the error dictionnary.

For the second, it's a mistake made during a recent reworking of the Exceptions pipeline. (#357)
