### ISSUE TITLE
Problem when importing item from wikidata to local instance

### ISSUE THREAD

**Issue by LizzAlice** [LeMyst/WikibaseIntegrator#456]
Previously, I was importing entities by getting the json information, processing them and writing them to a new entity.
However, as that generates quite a lot of code, I wanted to rewrite this to only use the wikibaseintegrator classes. At the moment, I do not want to import the claims, so I am setting them to an empty claims object.
```
    def test_get_wikidata_information(self, wikidata_id, languages):
        if wikidata_id[0] == "Q":
            entity = self.wikibase_integrator.item.get(entity_id=wikidata_id)
        elif wikidata_id[0] == "P":
            entity = self.wikibase_integrator.property.get(entity_id=wikidata_id)
        else:
            raise Exception(
                f"Wrong ID format, should start with P or Q but ID is {wikidata_id}"
            )
        if not languages == "all":
            # set labels in desired languages
            label_dict = {
                k: entity.labels.values[k]
                for k in languages
                if k in entity.labels.values
            }
            if not label_dict:
                raise Exception("No labels left when using these languages")
            entity.labels.values = label_dict
            # set descriptions in desired languages
            description_dict = {
                k: entity.descriptions.values[k]
                for k in languages
                if k in entity.descriptions.values
            }
            entity.descriptions.values = description_dict
            # set aliases in desired languages
            alias_dict = {
                k: entity.aliases.aliases[k]
                for k in languages
                if k in entity.aliases.aliases
            }
            entity.aliases.aliases = alias_dict
        from wikibaseintegrator.models.claims import Claims

        entity.claims = Claims()

        return entity
```

If I then change the config to my local instance and do an entity.write(), I get an MWApiError without further information. So, after sending it as follows for debugging:

```
def debug_write(self, entity):
        import ujson

        data = entity.get_json()

        payload = {
            "action": "wbeditentity",
            "data": ujson.dumps(data),
            "format": "json",
            "token": "+\\",
        }
        is_bot = self.wikibase_integrator.is_bot
        if is_bot:
            payload.update({"bot": ""})
        payload.update({"new": entity.type})
        login = self.wikibase_integrator.login

        from wikibaseintegrator.wbi_config import config

        mediawiki_api_url = config["MEDIAWIKI_API_URL"]
        user_agent = "WikibaseIntegrator/0.12.0"
        headers = {"User-Agent": user_agent}
        payload.update({"token": login.get_edit_token()})
        session = login.get_session()

        response = None
        import requests

        from time import sleep
        import json

        for n in range(100):
            try:
                response = session.request(
                    method="POST",
                    url=mediawiki_api_url,
                    data=payload,
                    headers=headers,
                )
            except requests.exceptions.ConnectionError as e:
                print("Connection error: %s. Sleeping for %d seconds.", e, 60)
                sleep(60)
                continue
            if response.status_code in (500, 502, 503, 504):
                print(
                    "Service unavailable (HTTP Code %d). Sleeping for %d seconds.",
                    response.status_code,
                    60,
                )
                sleep(60)
                continue
            break
        response.raise_for_status()
        print(response.content)
        print(response.request.body)
        print(response.request.headers)
        print(mediawiki_api_url)
        json_data = response.json()
        print(json_data)
        sys.exit("Exited")
```
I get an error with the info 'info': 'Invalid field used in call: "id", must match id parameter'. So, I set entity.id to None.
When using entity.write(), I get a MWApiError again.
When using the debug_write function, however, I get `{'entity': {'type': 'item', 'id': 'Q963', 'labels': {'en': {'language': 'en', 'value': 'part'}, 'de': {'language': 'de', 'value': 'Teil'}}, 'descriptions': {'en': {'language': 'en', 'value': 'separate element of a larger entity'}, 'de': {'language': 'de', 'value': 'einzelnes Teil einer größeren Entität'}}, 'aliases': {'en': [{'language': 'en', 'value': 'portion'}, {'language': 'en', 'value': 'piece'}, {'language': 'en', 'value': 'component'}, {'language': 'en', 'value': 'element'}], 'de': [{'language': 'de', 'value': 'Bestandteil'}]}, 'claims': {}, 'sitelinks': {}, 'lastrevid': 1928}, 'success': 1}` as response and the entity is present in the local instance.
This is a surprise to me, as I derived the write_debug function from the wikibaseintegrator code.
(I changed the item that gets imported to avoid checking for duplicates at this point)

**Comment by LeMyst** [comment]
@LizzAlice 
I've pushed a new branch named "add-as-new" who add a new parameter to the write() function to force the "new" field in the query and avoid adding incoherent fields (like id or baserevid).

Can you try if that improve your use-case?

If you want more debug info, you can try the logging module, add these lines at the beginning of your main file:
```
import logging
logging.basicConfig(level=logging.DEBUG)
```

I don't know how you switch from one Wikibase instance to another, but you can do it by simply passing some argument to the write/get function, you can also pass a different wbi_login object:
```
entity = wbi.property.get('5192', mediawiki_api_url='https://www.wikidata.org/w/api.php', login=login_wikidata)
[...]
entity.write(mediawiki_api_url='http://localhost/w/api.php', login=login_local, as_new=True)
```

**Comment by dpriskorn** [comment]
I usually have two different WBI instances when working with two wikibases. One reads from Wikidata and the other writes to my local wikibase.

**Comment by LizzAlice** [comment]
I tried the new param and it worked! Thank you! 
I wrote a function that changes the config for switching instances.

**Comment by LizzAlice** [comment]
Note: I still have to set entity.id to None manually, though

**Comment by LeMyst** [comment]
> Note: I still have to set entity.id to None manually, though

I don't think you need to set the id to None, with the parameter `as_new`, the id will be ignored.

**Comment by LizzAlice** [comment]
I commented it out and got the id Error again.

**Comment by dpriskorn** [comment]
Could you post a screenshot of the traceback?

**Comment by LizzAlice** [comment]
![image](https://user-images.githubusercontent.com/26574857/205059304-f6389cf7-11aa-43ad-abf3-4b23c388887b.png)

**Comment by LeMyst** [comment]
> I commented it out and got the id Error again.

Yeah, got the same issue, I kept old code when trying first time.
I'll try to manage this in the `as_new` parameter, but that don't seems to be simple, don't know why.

**Comment by LizzAlice** [comment]
Great, now it works, thank you!

**Comment by dpriskorn** [comment]
Wohoo 😀
