### ISSUE TITLE
GUID invalid for given entity

### ISSUE THREAD

**Issue by LizzAlice** [LeMyst/WikibaseIntegrator#471]
I am still trying to import items/properties with their claims from wikidata into my local instance.
This is what I am doing (in case there is a cleaner option, please let me know).
I am pulling an entity from wikidata, looking up the property/item ids contained in its claims/references/qualifiers, importing those into my local instance without their statements and then replacing their wikidata ids in the entity by my own local ids. This seems to work now. 
However, the resulting claims look like this:
_'claims': {'P2': [{'mainsnak': {'snaktype': 'value$, 'property': 'P31', 'datatype': 'wikibase-item', 'datavalue': {'value': {'entity-type': 'item', 'numeric-id': '262', 'id': 'Q262'}, 'type': 'wikibase-entityid'}}, 'type': 'statement', 'id': 'Q115681322$43def00c-4ff0-f8bf-3952-33979a4e42b0', 'rank': 'normal'}, ..._
As you can see, the id (_'id': 'Q115681322$43def00c-4ff0-f8bf-3952-33979a4e42b0'_) still contains the original entity id, which is probably why I am getting the error message _wikibaseintegrator.wbi_exceptions.ModificationFailed: 'Statement GUID invalid for given entity'_ when trying to write the entity.
I tried setting the id to None, as the documentation says that it is optional, however, then I get the error message: _wikibaseintegrator.wbi_exceptions.ModificationFailed: 'Statement GUID can not be parsed'_
I tried removing the id completely using pop(), but that gave me a _KeyError,_ because it is used in claims.py.
Is there any way of generating a new id or setting it to None in a way that doesn't throw an error?

**Comment by LeMyst** [comment]
Hello @LizzAlice 

I tried to copy an item from Wikidata to Test Wikidata, and it seems ok for me :
```python
entity = wbi.item.get('Q582', mediawiki_api_url='https://www.wikidata.org/w/api.php', login=login_wikidata)
new_claim = entity.claims.get('P485')[0]  # P485 have only one statement, got the first one
new_claim.mainsnak.datavalue['value']['id'] = 'Q87349'  # Replace item name
new_claim.mainsnak.datavalue['value']['numeric-id'] = 87349  # Replace the idem numeric id
new_claim.qualifiers = Qualifiers()  # Reset the qualifiers, to not deal with them
new_claim.id = None  # Set the id to None, because it's a new one
entity.claims = Claims().add(new_claim)
entity.write(mediawiki_api_url='https://test.wikidata.org/w/api.php', login=login_testwikidata, as_new=True)
```

can you share your code with us?

**Comment by LizzAlice** [comment]
This is my code. I left out the references and qualifiers for readability.

```
entity_names = [
      "wikibase-item",
       "wikibase-property",
        "wikibase-lexeme",
]

claims = entity.claims.claims
new_claims = {}
for prop_id, claim_list in claims.items():
      local_claim_list = []
      # this imports a claim entity w/o the statements
      local_prop_id = self.write_claim_entities(
                wikidata_id=prop_id, languages=languages, login=login
            )
      if not local_prop_id:
           print("local id skipped")
           continue
      for c in claim_list:
            c_dict = c.get_json()
            if c_dict["mainsnak"]["datatype"] in entity_names:
                 if c_dict["mainsnak"]["datavalue"]:
                        local_mainsnak_id = self.write_claim_entities(
                            wikidata_id=c_dict["mainsnak"]["datavalue"]["value"]["id"],
                            languages=languages,
                            login=login,
                        )
                        if not local_mainsnak_id:
                            continue
                        c_dict["mainsnak"]["datavalue"]["value"][
                            "id"
                        ] = local_mainsnak_id
                        c_dict["mainsnak"]["datavalue"]["value"][
                            "numeric-id"
                        ] = local_mainsnak_id[1:]
                        c_dict["mainsnak"]["property"] = local_prop_id
                        new_c = Claim().from_json(c_dict)
                 else:
                       continue
                 new_c.references.references = Reference()
                 new_c.qualifiers = Qualifiers()
                 local_claim_list.append(new_c)
     new_claims[local_prop_id] = local_claim_list
entity.claims.claims = new_claims
entity.write(login=login, as_new=True)
```

**Comment by LizzAlice** [comment]
Happy new year! Are there any news on this?

**Comment by LeMyst** [comment]
I tried to change the property id, and it's Ok too, with v0.12.3.dev0 (master branch) :
```python
entity = wbi.item.get('Q582', mediawiki_api_url='https://www.wikidata.org/w/api.php', login=login_wikidata)
new_claim = entity.claims.get('P485')[0]  # P485 have only one statement, got the first one
new_claim.mainsnak.property_number = 'P17889'
new_claim.mainsnak.datavalue['value']['id'] = 'Q87349'  # Replace item name
new_claim.mainsnak.datavalue['value']['numeric-id'] = 87349  # Replace the idem numeric id
new_claim.qualifiers = Qualifiers()  # Reset the qualifiers, to not deal with them
new_claim.id = None  # Set the id to None, because it's a new one
entity.claims = Claims().add(new_claim)
entity.write(mediawiki_api_url='https://test.wikidata.org/w/api.php', login=login_testwikidata, as_new=True)
```

https://test.wikidata.org/wiki/Q229032

**Comment by LizzAlice** [comment]
Found it, I was setting it to None by doing `c_dict["id"] = None`, when I do it your way, it works. I thought this was the same thing, as c_dict gets read from json to a claim.
