### ISSUE TITLE
add reset_id helper method

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#472]
as a user I dont want to think about how to reset an id
See https://github.com/LeMyst/WikibaseIntegrator/issues/471

**Comment by LeMyst** [comment]
Hello @dpriskorn ,

I understand your request, but why is the difference between:
`new_claim.id = None`
and
`new_claim.reset_id()`

or if you want to add the reset_id() method somewhere else?

**Comment by dpriskorn** [comment]
The second leaves the implementation details to WBI and follows Don't make me think. See https://en.wikipedia.org/wiki/Don't_Make_Me_Think?wprov=sfti1
