### ISSUE TITLE
as a developer I want helper methods that help me quantify the entity

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#515]
Eg number of statements, number of senses, number of forms.

**Comment by LeMyst** [comment]
Hello Dennis,
I'm not sure to understand the gain between:
`count = len(lexeme.senses)`
and
`count = lexeme.number_of_senses()`

**Comment by dpriskorn** [comment]
As a user I don't have to think. Also that code snippet does not work. 😉
Lexeme.senses.senses is the list.

**Comment by LeMyst** [comment]
Does https://github.com/LeMyst/WikibaseIntegrator/pull/517 answer this ?
I prefer len(), and I think it's more common for the user.
