### ISSUE TITLE
As a user I want a method on al entities, forms and senses that gives me the URI to the entity

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#516]
For example if I download a lexeme with lexeme.get() and iterate through the forms of a lexeme I want to be able to call form.uri and get e.g. http://www.wikidata.org/wiki/Lexeme:L1#F1 as a string. 

This should of course use the wikibase config to generate the uri

**Comment by LeMyst** [comment]
Does #537 help you?

**Comment by dpriskorn** [comment]
> Does #537 help you?

Only partly. Does it support sense and form URLs also?

**Comment by LeMyst** [comment]
I'm trying to find out more information about the url entity for the declaration/meaning/form and whether it is perennial.

**Comment by dpriskorn** [comment]
I don't understand. Did you see my implementation?
Just add the form I'd or sense I'd to the Wikidata url. 
They don't have URIs like identities.
