### ISSUE TITLE
Support Wikibase CLI json format

### ISSUE THREAD

**Issue by WolfgangFahl** [LeMyst/WikibaseIntegrator#527]
https://github.com/maxlath/wikibase-cli support a json format for manipulating wikidata.
See https://github.com/maxlath/wikibase-edit/blob/main/docs/how_to.md#create-entity

In our restful endpoint for CEUR-WS we support generating wbjson and would love to directly be able to use the json format via python without having to resort the the command line.

Example:
* https://www.wikidata.org/wiki/Q117351503 has been created from
* http://ceurspt.wikidata.dbis.rwth-aachen.de/Vol-3170/paper3.wbjson
see 
* http://ceurspt.wikidata.dbis.rwth-aachen.de/Vol-3170/paper3.html

We think this approach is better than Quickstatements
* http://ceurspt.wikidata.dbis.rwth-aachen.de/Vol-3170/paper3.qs (incompletely implemented)

**Comment by LeMyst** [comment]
Hello @WolfgangFahl 
Does something like in #534 can help you?

**Comment by WolfgangFahl** [comment]
@LeMyst  thx - i'll have to try that out in the upcoming days.
