### ISSUE TITLE
This regex is missing L so that the library works on lexemes also

### ISSUE THREAD

**Issue by egils-consulting** [LeMyst/WikibaseIntegrator#54]
https://github.com/LeMyst/WikibaseIntegrator/blob/30c2f766931f442a2ec7160073331811859a840d/wikibaseintegrator/wbi_core.py#L2043

**Comment by LeMyst** [comment]
You can use Lexeme in claim with wbi_core.Lexeme

**Comment by egils-consulting** [comment]
Does wbi support lexeme forms?
I need to point on a form when adding a usage examples with the property "demonstrates form".

**Comment by egils-consulting** [comment]
There is no way to write to a lexeme because this is the only parameters to ItemEngine:
def __init__(self, item_id='', new_item=False, data=None, mediawiki_api_url=None, sparql_endpoint_url=None,
                 wikibase_url=None, append_value=None, fast_run=False, fast_run_base_filter=None,
                 fast_run_use_refs=False, ref_handler=None, global_ref_mode='KEEP_GOOD', good_refs=None,
                 keep_good_ref_statements=False, search_only=False, item_data=None, user_agent=None, core_props=None,
                 core_prop_match_thresh=0.66, property_constraint_pid=None, distinct_values_constraint_qid=None,
                 fast_run_case_insensitive=False, debug=False):

and item_id there invokes the regex I referenced above.

**Comment by egils-consulting** [comment]
So yes with wbi_core.Lexeme you can add a lexeme to a claim but only save it to a QID in the end.

**Comment by egils-consulting** [comment]
> So yes with wbi_core.Lexeme you can add a lexeme to a claim but only save it to a QID in the end.

this assertion is false, I just got it to send the edited lexeme to the api (and got an api error).
