### ISSUE TITLE
Add a property as a value

### ISSUE THREAD

**Issue by lubianat** [LeMyst/WikibaseIntegrator#551]
Hello! I am trying to add a property as a value using WikibaseIntegrator, but that does not seem to be supported:

```
        wbi = WikibaseIntegrator(login=login_instance)
        prop = wbi.property.new(datatype="wikibase-item")
        prop.labels.set(language="en", value="inverse")
        prop.descriptions.set(language="en", value="machine-generated property")
        data = [
            Property(
                value="P1",
                prop_nr="P2"
,
            )
        ]
        prop.claims.add(data)
        new_property = prop.write()
```

for which I get:

```
wikibaseintegrator.wbi_exceptions.ModificationFailed: 'Unexpected entity type property'
```

Any suggestions on how to do it? 

Thanks for the great tool, by the way!!

**Comment by LeMyst** [comment]
Hello @lubianat ,

I tried your code on test.wikidata without issue and with latest WikibaseIntegrator.

What's the property type of your Property P2 ?
I think maybe it's not "property" but something else.

**Comment by lubianat** [comment]
Oh, oops! It is "Item", you are correct.

Sorry about that.
Best,
Tiago




Em seg., 5 de jun. de 2023 às 20:28, Myst ***@***.***>
escreveu:
