### ISSUE TITLE
When creating lexemes, bad values for "dct:languages" are accepted

### ISSUE THREAD

**Issue by dlindem** [LeMyst/WikibaseIntegrator#552]
As described at [T338255](https://phabricator.wikimedia.org/T338255), a bot that used WBI has created lexemes. The source data passed to WBI contained values preceded by "wd:" for "dct:language" (wd:Q397 for Latin in these cases). WBI wrote these values to Wikidata without raising a validation error, and Wikidata accepted these values. If I understand that right, it would be good to change the validation regex for values like "Q397" so that if anything precedes the "Q" that value is rejected. Astonishingly, Wikidata accepted those "wd:"-preceded values, and displayed the language in the interface correctly ("Latin"), but as stated in the cited phabricator ticket it failed processing those values in the indexation for search.

**Comment by LeMyst** [comment]
Hello @dlindem ,

Thank you for the alert.
I will look into this later today.
