### ISSUE TITLE
Malformed input when entering text with newlines ('\n')

### ISSUE THREAD

**Issue by lubianat** [LeMyst/WikibaseIntegrator#561]
I am getting the folowing error: 

```
Exception has occurred: ModificationFailed
"Malformed input: Refill Nouns Strategic Funding Works (NSFW) Pool Refill Nouns Strategic Funding Works (NSFW) Pool Nouns Strategic Funding Works (NSFW), formerly Small Grants, is running low on ETH and needs to be refilled. NSFW is a pool of capital that serves the DAO's interest, stewarded on a completely discretionary basis by the group's members, and funds things that include: * Small Grants * Retro Rewards * Residencies * Trials ahead of sponsoring on-chain proposals * Ad hoc DAO needs - contests, bug bounties, being the DAO’s “hot wallet” The group conducts its daily operations in the Discord in the -and-retro-funding-channel, as well as on the Nouns [Discourse forum]( **[This link contains information on everything NSFW has ever funded.]( Previous NSFW Proposals: * [Prop 13 - 20 ETH Inception]( * [Prop 31 - 50 ETH Refill]( * [Prop 43 - 100 ETH Refill]( * [Prop 85 - 200 ETH Refill]( * [Prop 111 - Noun 22 Contract Extension]( * 111 contains more detailed context on NSFW's role in the DAO and its day to day operations. This proposal also funded NSFW with 50 ETH."
  File "/home/lubianat/Documents/wiki_related/kudos_wikibase/src/add_triples_to_proposals.py", line 94, in <module>
    item.write()
wikibaseintegrator.wbi_exceptions.ModificationFailed: "Malformed input: Refill Nouns Strategic Funding Works (NSFW) Pool Refill Nouns Strategic Funding Works (NSFW) Pool Nouns Strategic Funding Works (NSFW), formerly Small Grants, is running low on ETH and needs to be refilled. NSFW is a pool of capital that serves the DAO's interest, stewarded on a completely discretionary basis by the group's members, and funds things that include: * Small Grants * Retro Rewards * Residencies * Trials ahead of sponsoring on-chain proposals * Ad hoc DAO needs - contests, bug bounties, being the DAO’s “hot wallet” The group conducts its daily operations in the Discord in the -and-retro-funding-channel, as well as on the Nouns [Discourse forum]( **[This link contains information on everything NSFW has ever funded.]( Previous NSFW Proposals: * [Prop 13 - 20 ETH Inception]( * [Prop 31 - 50 ETH Refill]( * [Prop 43 - 100 ETH Refill]( * [Prop 85 - 200 ETH Refill]( * [Prop 111 - Noun 22 Contract Extension]( * 111 contains more detailed context on NSFW's role in the DAO and its day to day operations. This proposal also funded NSFW with 50 ETH."
```

I actually get this error with different strings, all of them containing some kind of markup, usually different types of quotes. 

Any idea on what might be happening? 

The code works fine for strings with no markup (e.g. https://nounsdev.wikibase.cloud/wiki/Item:Q107#P17)

**Comment by LeMyst** [comment]
Hello @lubianat 
Can you paste an example of string you try to use? (I tried the one in your error message, but a quick test show no issue)

Thanks

**Comment by lubianat** [comment]
Here is one such example: 
```
Allocate Noun to Lil Nouns DAO - "treasure quest" edition

Replaces Proposal 76: 

Instead of directly allocating Noun to the Lil Nouns DAO treasury, create an on-chain offer only fillable by Lil Nouns treasury. 

Lil Nouns will have to successfully pass a governance proposal of their own to accept this offer.
There is no mention of a team or builder in this proposal
Allocate Noun to Lil Nouns DAO - "treasure quest" edition
```

**Comment by lubianat** [comment]
Code snippet: 

```
            object_name = """
            Allocate Noun to Lil Nouns DAO - "treasure quest" edition

Replaces Proposal 76: 

Instead of directly allocating Noun to the Lil Nouns DAO treasury, create an on-chain offer only fillable by Lil Nouns treasury. 

Lil Nouns will have to successfully pass a governance proposal of their own to accept this offer.
There is no mention of a team or builder in this proposal
Allocate Noun to Lil Nouns DAO - "treasure quest" edition
            
            
            """
            data.append(
                String(value=object_name, prop_nr=properties_in_wikibase[property_name])
            )

```

**Comment by lubianat** [comment]
Traceback (most recent call last):
  File "/home/lubianat/Documents/base_venv/lib/python3.8/site-packages/wikibaseintegrator/entities/baseentity.py", line 237, in _write
    json_result: dict = edit_entity(data=data, id=entity_id, type=self.type, summary=summary, clear=clear, is_bot=is_bot, allow_anonymous=allow_anonymous,
  File "/home/lubianat/Documents/base_venv/lib/python3.8/site-packages/wikibaseintegrator/wbi_helpers.py", line 332, in edit_entity
    return mediawiki_api_call_helper(data=params, is_bot=is_bot, **kwargs)
  File "/home/lubianat/Documents/base_venv/lib/python3.8/site-packages/wikibaseintegrator/wbi_helpers.py", line 214, in mediawiki_api_call_helper
    return mediawiki_api_call('POST', mediawiki_api_url=mediawiki_api_url, session=session, data=data, headers=headers, max_retries=max_retries, retry_after=retry_after, **kwargs)
  File "/home/lubianat/Documents/base_venv/lib/python3.8/site-packages/wikibaseintegrator/wbi_helpers.py", line 124, in mediawiki_api_call
    raise ModificationFailed(json_data['error'])
wikibaseintegrator.wbi_exceptions.ModificationFailed: 'Malformed input: Allocate Noun to Lil Nouns DAO - "treasure quest" edition Replaces Proposal 76: Instead of directly allocating Noun to the Lil Nouns DAO treasury, create an on-chain offer only fillable by Lil Nouns treasury. Lil Nouns will have to successfully pass a governance proposal of their own to accept this offer. There is no mention of a team or builder in this proposal Allocate Noun to Lil Nouns DAO - "treasure quest" edition'

**Comment by lubianat** [comment]
I'm trying to debug it on my end.

A blank "test" string goes just fine. 

@LeMyst  Found the issue: new lines cause malformed inputs.

Bug is fixed by:
```
            if "\n" in object_name:
                object_name = object_name.replace("\n", " - ")
            data.append(
                String(value=object_name, prop_nr=properties_in_wikibase[property_name])
            )
```

**Comment by LeMyst** [comment]
I'll add a test to raise an exception if you add newline in your String

**Comment by lubianat** [comment]
awesome, thanks so much!
Tiago




Em seg., 12 de jun. de 2023 às 11:42, Myst ***@***.***>
escreveu:
