### ISSUE TITLE
Support for ttl output is first stepping stone to validate using pyshex

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#589]
We need ttl support if we want to use pyshex
e.g. get_ttl_representation()

**Comment by LeMyst** [comment]
ttl scope is very large, larger than what support WikibaseIntegrator today or what WBI can easily support.

Do you want a 1:1 (wbi:wikidata) ttl representation? Or partial support is enough for pyshex?

**Comment by dpriskorn** [comment]
I was thinking we have a method that just download it as a string.
get_ttl_as_string()
