### ISSUE TITLE
ActionIfExistis --> APPEND or ADD REFERENCE

### ISSUE THREAD

**Issue by lubianat** [LeMyst/WikibaseIntegrator#607]
I have a situation where a bot adds a previously existing statement: 

https://www.wikidata.org/w/index.php?title=Q10357327&diff=prev&oldid=1954324483&diffmode=source 

I wanted some behaviour that both kept the past reference block and added a new one.

 Do you know if that is possible? 

Thanks!

**Comment by LeMyst** [comment]
Hello @lubianat 

Can you share the code you use to add the reference ?

**Comment by LeMyst** [comment]
```
item = wbi.item.get('Q124264')
reference = Reference()
reference.add(datatypes.Item(prop_nr='P149', value='Q124264'))
item.claims.get('P63600')[0].references.add(reference=reference)
```

This work correctly for me.
1. get the item
2. create a new empty reference
3. update the reference with wanted values
4. add the new reference to the existing referenceS

**Comment by lubianat** [comment]
Thanks!
 I was not explicitly trying to add a new reference, but add new statements
that could eventually be present.

It is basically

```
            open_targets_reference = Reference()
            open_targets_reference.add(
                datatypes.Item(prop_nr="P248", value="Q113138000")
            )
            open_targets_reference.add(
                datatypes.Time(
                    "+2023-08-14T00:00:00Z",
                    prop_nr="P813",
                )
            )
            claims_json = item.claims.get_json()
            for claim in claims_json:
                if claims_json[claim][0]["mainsnak"]["property"] == "P592":
                    chembl_id =
claims_json[claim][0]["mainsnak"]["datavalue"]["value"]

            open_targets_reference.add(
                datatypes.URL(
                    f"https://platform.opentargets.org/drug/{chembl_id}",
                    prop_nr="P854",
                )
            )
            all_references.add(open_targets_reference)
            # Update the item on Wikidata
            claim = datatypes.Item(
                prop_nr="P129",
                value=obj_wd,
                qualifiers=qualifiers,
                references=all_references,
            )

            item.claims.add(claim,
action_if_exists=ActionIfExists.APPEND_OR_REPLACE)
```
From
https://github.com/lubianat/opentargets2wikidata/blob/master/src/add_linked_targets_to_wikidata.py
Tiago

**Comment by LeMyst** [comment]
Maybe what you want to do is not possible at this moment with WikibaseIntegrator.

You can "merge" an existing claim (same value) with your claim. If you want to do this, you need to get the claim, update it and replace the existing.
If you want to append a new claim (multiple claims with the same values) you can use the ActionIfExists.FORCE_APPEND.

Currently, the ActionIfExists.APPEND_OR_REPLACE replace the existing claim when the same value is found, it's what happens in your first message.

Maybe a ActionIfExists.APPEND_OR_MERGE will be a good way to do it, merge the references/qualifiers with the existing claim. It's what you want to do?

**Comment by lubianat** [comment]
This is the code bit that controls how statements are added, right? 

https://github.com/LeMyst/WikibaseIntegrator/blob/6cf9c270fb9f48265ecc63f036f1d6008db9ae38/wikibaseintegrator/wbi_fastrun.py#L209

Is there any other place? 

I might try and implement this myself

**Comment by LeMyst** [comment]
Instead you are using fastrun (I highly doubt), it's more likely this line you search:

https://github.com/LeMyst/WikibaseIntegrator/blob/6cf9c270fb9f48265ecc63f036f1d6008db9ae38/wikibaseintegrator/models/claims.py#L85C67-L85C67

**Comment by lubianat** [comment]
By the way, I've implemented ActionIfExists.MERGE_REFS_OR_APPEND, I'll open a pull request with the changes so we can iterate from there :) Ok for you, @LeMyst ? 

![image](https://github.com/LeMyst/WikibaseIntegrator/assets/7917951/411ebc98-98f9-4c85-9896-77f868a14ffd)


Here is the snippet: 

```
                elif action_if_exists == ActionIfExists.MERGE_REFS_OR_APPEND:
                    claim_exists = False
                    for existing_claim in self.claims[property]:
                        existing_claim_json = existing_claim.get_json()
                        claim_to_add_json = claim.get_json()
                        # Check if the value of the claim exists
                        if (
                            claim_to_add_json["mainsnak"]["datavalue"]["value"]
                            == existing_claim_json["mainsnak"]["datavalue"]["value"]
                        ):
                            claim_exists = True
                            # Check if the references are identical
                            if not Claim.refs_equal(claim, existing_claim):
                                # If they're different, add the new reference block
                                for ref_to_add in claim.references:
                                    existing_claim.references.add(ref_to_add)

                            break

                    # If the claim value does not exist, append it
                    if not claim_exists:
                        self.claims[property].append(claim)
```

**Comment by dpriskorn** [comment]
I ran into this issue today, see https://github.com/dpriskorn/WikidataEurLexScraper/issues/2
