### ISSUE TITLE
Implement watchlist support?

### ISSUE THREAD

**Issue by egils-consulting** [LeMyst/WikibaseIntegrator#62]
Hi. I need to add the lexeme that is edited the watchlist. pywikibot supports that, but then my script would use first this library, then lexdata and then pywikibot and it seems like overkill to me.

Are you interested in supporting adding to watchlist in this library?
The code to do it in pywikibot is here:
https://phabricator.wikimedia.org/diffusion/PWBC/browse/master/pywikibot/site/__init__.py$4172
and the API is simple:
https://www.mediawiki.org/wiki/API:Watch

**Comment by LeMyst** [comment]
I'm sorry, but I don't think it's the purpose of this library to manage anything more than wikibase's functionalities.

**Comment by egils-consulting** [comment]
OK, I'll probably create my own little library that uses the login.py to do all the session work.
Is it possible for me to import and use just login.py as a module?
Something like
from wikibaseintegrator import login
?
