### ISSUE TITLE
Documentation for References + Reference

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#647]
I forgot how to use the References class and went through a bit of trial-and-error today.

I found no examples in the readme or notebooks where it is used.

I suggest we add that, see https://github.com/dpriskorn/WikidataEurLexScraper/blob/f82266fbd98d72e8b800d3256963513103253ff1/main.py#L188 for an example

**Comment by LeMyst** [comment]
Hello Dennis,

I've prepared a MR to add "common use cases" to the README, with references to the Jupyter Notebook:
https://github.com/LeMyst/WikibaseIntegrator/pull/650

Do you think that can help you in the future?

**Comment by dpriskorn** [comment]
Yes, exactly what I needed to remember 😀
