### ISSUE TITLE
Introduce new Enum for time precision

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#656]
E.g 
WikibasePrecision(Enum):
DAY=11,
etc.

**Comment by LeMyst** [comment]
Hello dennis,

There is already WikibaseDatePrecision : https://github.com/LeMyst/WikibaseIntegrator/blob/d32ac9bb8ab877243d5d89824ed9d56ad2e49d98/wikibaseintegrator/wbi_enums.py#L58C7-L58C28
