### ISSUE TITLE
How to make wbi append?

### ISSUE THREAD

**Issue by egils-consulting** [LeMyst/WikibaseIntegrator#66]
see https://github.com/egils-consulting/LexUse/blob/8304344865562a2c92ea22eba7855cda8e4f1de4/swedish.py#L285 and https://www.wikidata.org/w/index.php?title=Lexeme%3AL239358&type=revision&diff=1327589795&oldid=1327585420

It replaces the old usage example instead of appending a value

**Comment by LeMyst** [comment]
Hello,

You can use the append_value from wbi_core.ItemEngine if you want to append value of certains properties.

Next time, to ask questions, use the "Discussions" function of GitHub :
https://github.com/LeMyst/WikibaseIntegrator/discussions
