### ISSUE TITLE
Append_value is not documented in the readme

### ISSUE THREAD

**Issue by egils-consulting** [LeMyst/WikibaseIntegrator#70]

**Comment by LeMyst** [comment]
I'll change how append works with this PR:
https://github.com/LeMyst/WikibaseIntegrator/pull/67

**Comment by egils-consulting** [comment]
Looks promising, what is needed to merge it?

**Comment by LeMyst** [comment]
> Looks promising, what is needed to merge it?

More testing

**Comment by egils-consulting** [comment]
Wii 😃 Are you planning a release?

**Comment by LeMyst** [comment]
@egils-consulting 
ASAP, I currently test the build on my own wikibase.
I've one issue with the unit support and require_write at the moment.

**Comment by LeMyst** [comment]
> Wii 😃 Are you planning a release?

Hi @egils-consulting 
v0.10.0 has been released.
Look at the changelog:
https://github.com/LeMyst/WikibaseIntegrator/releases/tag/v0.10.0

**Comment by egils-consulting** [comment]
Wow, I'm impressed. I'll test it out soon 😃
