### ISSUE TITLE
Obtaining Recent Changes

### ISSUE THREAD

**Issue by Superraptor** [LeMyst/WikibaseIntegrator#731]
Is it possible to utilize WikibaseIntegrator in order to query for recent changes to a Wikibase? Thanks so much!

**Comment by LeMyst** [comment]
Hello @Superraptor ,

WikibaseIntegrator main goal is to manipulate data on Wikibase instances, so it's not primarily designed to get recent changes.
But you can use the Mediawiki API trough WikibaseIntegrator helpers to get te informations you want.
The API example on the sandbox :
https://www.wikidata.org/wiki/Special:ApiSandbox#action=query&format=json&list=recentchanges&formatversion=2

You have an example in the README:
https://github.com/LeMyst/WikibaseIntegrator?tab=readme-ov-file#use-mediawiki-api

And an succinct code example:
```python
from wikibaseintegrator.wbi_helpers import mediawiki_api_call_helper

data = {
    'action': 'query',
    'format': 'json',
    'list': 'recentchanges'
}

print(mediawiki_api_call_helper(data=data, allow_anonymous=True, user_agent='Myst/0.1 Test get recentchanges')['query']['recentchanges'])
```

I hope this help you.
