### ISSUE TITLE
Adding more than 2 qualifiers to a claim gives mwapi error

### ISSUE THREAD

**Issue by egils-consulting** [LeMyst/WikibaseIntegrator#75]
Hi, yesterday I tried adding 4 qualifiers to a claim with wbi and got an mwapi error.
2 qualifiers worked fine.
Details will follow

**Comment by LeMyst** [comment]
Any news about the issue?

**Comment by egils-consulting** [comment]
<pre>
DEBUG:root:claim:{'mainsnak': {'snaktype': 'value', 'property': 'P5831', 'datavalue': {'value': {'text': 'Studenten skulle också vara underbefäl, och plåtslagaren hade kommit under de uttagna 14 procenten.', 'language': 'sv'}, 'type': 'monolingualtext'}, 'datatype': 'monolingualtext'}, 'type': 'statement', 'rank': 'normal', 'qualifiers': {'P5830': [{'snaktype': 'value', 'property': 'P5830', 'datavalue': {'value': {'entity-type': 'form', 'id': 'L63696-F2'}, 'type': 'wikibase-entityid'}, 'datatype': 'wikibase-form'}], 'P6072': [{'snaktype': 'value', 'property': 'P6072', 'datavalue': {'value': {'entity-type': 'sense', 'id': 'L63696-S1'}, 'type': 'wikibase-entityid'}, 'datatype': 'wikibase-sense'}], 'mainsnak': {'snaktype': 'value', 'property': 'P3865', 'datavalue': {'value': {'entity-type': 'item', 'numeric-id': 47461344, 'id': 'Q47461344'}, 'type': 'wikibase-entityid'}, 'datatype': 'wikibase-item'}, 'type': 'statement', 'rank': 'normal', 'qualifiers': {}, 'qualifiers-order': [], 'references': []}, 'qualifiers-order': ['P5830', 'P6072', 'P6191', 'P3865'], 'references': [{'snaks': {'P248': [{'snaktype': 'value', 'property': 'P248', 'datavalue': {'value': {'entity-type': 'item', 'numeric-id': 21592569, 'id': 'Q21592569'}, 'type': 'wikibase-entityid'}, 'datatype': 'wikibase-item'}], 'P8433': [{'snaktype': 'value', 'property': 'P8433', 'datavalue': {'value': 'DL9C10', 'type': 'string'}, 'datatype': 'external-id'}], 'P813': [{'snaktype': 'value', 'property': 'P813', 'datavalue': {'value': {'time': '+2021-01-05T00:00:00Z', 'timezone': 0, 'before': 0, 'after': 0, 'precision': 11, 'calendarmodel': 'http://www.wikidata.org/entity/Q1985727'}, 'type': 'time'}, 'datatype': 'time'}], 'P577': [{'snaktype': 'value', 'property': 'P577', 'datavalue': {'value': {'time': '+1924-01-01T00:00:00Z', 'timezone': 0, 'before': 0, 'after': 0, 'precision': 11, 'calendarmodel': 'http://www.wikidata.org/entity/Q1985727'}, 'type': 'time'}, 'datatype': 'time'}]}, 'snaks-order': ['P248', 'P8433', 'P813', 'P577']}]}
Logging in with Wikibase Integrator
Error while writing to the Wikibase instance
Traceback (most recent call last):
  File "/home/user/src/python/lexuse/swedish.py", line 49, in <module>
    main()
  File "/home/user/src/python/lexuse/swedish.py", line 45, in main
    util.process_lexeme_data(results)
  File "/home/user/src/python/lexuse/util.py", line 686, in process_lexeme_data
    process_result(result, data)
  File "/home/user/src/python/lexuse/util.py", line 596, in process_result
    result = present_sentence(
  File "/home/user/src/python/lexuse/util.py", line 499, in present_sentence
    result = add_usage_example(
  File "/home/user/src/python/lexuse/util.py", line 308, in add_usage_example
    result = item.write(
  File "/usr/lib/python3.9/site-packages/wikibaseintegrator/wbi_core.py", line 1008, in write
    raise MWApiError(json_data)
wikibaseintegrator.wbi_core.MWApiError: {'error': {'code': 'invalid-claim', 'info': 'The snak serialization should be an array', 'messages': [{'name': 'wikibase-api-invalid-claim', 'parameters': ['The snak serialization should be an array'], 'html': {'*': 'The snak serialization should be an array'}}], '*': 'See https://www.wikidata.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.'}, 'servedby': 'mw1283'}
</pre>
Code is here https://github.com/egils-consulting/LexUse/blob/2073fa71630850e71e4952afbe384870c8cbdcec/util.py#L286
If I comment out the to last qualifiers on line 289 and 290 it works:
<pre>
DEBUG:root:claim:{'mainsnak': {'snaktype': 'value', 'property': 'P5831', 'datavalue': {'value': {'text': 'För dem som inte åker egen bil kan långfärdsbuss vara ett ekonomiskt tilltalande alternativ.', 'language': 'sv'}, 'type': 'monolingualtext'}, 'datatype': 'monolingualtext'}, 'type': 'statement', 'rank': 'normal', 'qualifiers': {'P5830': [{'snaktype': 'value', 'property': 'P5830', 'datavalue': {'value': {'entity-type': 'form', 'id': 'L60957-F5'}, 'type': 'wikibase-entityid'}, 'datatype': 'wikibase-form'}], 'P6072': [{'snaktype': 'value', 'property': 'P6072', 'datavalue': {'value': {'entity-type': 'sense', 'id': 'L60957-S1'}, 'type': 'wikibase-entityid'}, 'datatype': 'wikibase-sense'}]}, 'qualifiers-order': ['P5830', 'P6072'], 'references': [{'snaks': {'P248': [{'snaktype': 'value', 'property': 'P248', 'datavalue': {'value': {'entity-type': 'item', 'numeric-id': 21592569, 'id': 'Q21592569'}, 'type': 'wikibase-entityid'}, 'datatype': 'wikibase-item'}], 'P8433': [{'snaktype': 'value', 'property': 'P8433', 'datavalue': {'value': 'GF02T18', 'type': 'string'}, 'datatype': 'external-id'}], 'P813': [{'snaktype': 'value', 'property': 'P813', 'datavalue': {'value': {'time': '+2021-01-05T00:00:00Z', 'timezone': 0, 'before': 0, 'after': 0, 'precision': 11, 'calendarmodel': 'http://www.wikidata.org/entity/Q1985727'}, 'type': 'time'}, 'datatype': 'time'}], 'P577': [{'snaktype': 'value', 'property': 'P577', 'datavalue': {'value': {'time': '+1992-04-01T00:00:00Z', 'timezone': 0, 'before': 0, 'after': 0, 'precision': 11, 'calendarmodel': 'http://www.wikidata.org/entity/Q1985727'}, 'type': 'time'}, 'datatype': 'time'}]}, 'snaks-order': ['P248', 'P8433', 'P813', 'P577']}]}
Logging in with Wikibase Integrator
DEBUG:root:result from WBI:L60957
Successfully added usage example to http://www.wikidata.org/entity/L60957
</pre>
Version:
$ pip list |grep wikibasei
wikibaseintegrator 0.9.0

**Comment by LeMyst** [comment]
I think the is_qualifier=True are missing

Yes, the error message is not explicit. I will work on this after my big patch for if_exists
