### ISSUE TITLE
Bug: Sitelinks not published

### ISSUE THREAD

**Issue by dabu1111** [LeMyst/WikibaseIntegrator#763]
Hi,

I realized that in the latest version (0.12.7) the item sitelinks won't be published Instead, they are overwritten by an empty Sitelinks() on each item.write() operation. 

I will create a PR in a minute to fix.

Cheers!

**Comment by LeMyst** [comment]
Hello @dabu1111 
Thank you for you PR, i've merged it.

**Comment by lubianat** [comment]
Thank you for this patch! it has just saved me :)
