### ISSUE TITLE
Add missing WikibaseTimePrecision values

### ISSUE THREAD

**Issue by tholzheim** [LeMyst/WikibaseIntegrator#784]
Currently the time precision values  `[1,2,5]` are missing in WikibaseTimePrecision leading to errors when editing pages that contain these precision values in one of their snaks. 

https://github.com/LeMyst/WikibaseIntegrator/blob/389a84d442c4f8e852ceb03e9192cbe97d08820e/wikibaseintegrator/wbi_enums.py#L61-L73

[Query to get a sample for each time precision](https://w.wiki/Bws$)

>Documentation on the missing precison values is hard to find but the Wikidata user interface provides their names in the precision dropdown selection.
>![Screenshot from 2024-11-07 00-21-21](https://github.com/user-attachments/assets/964ee1bc-2f67-4478-a01c-7689814f0343)

**Comment by LeMyst** [comment]
Hello,
Thanks, I used https://www.wikidata.org/wiki/Help:Dates#Precision to create the list and 1, 2 and 5 are missing from here.
Gonna merge the PR and maybe update the list.
