### ISSUE TITLE
add a reference, following the 'A Minimal Bot for Mass Import'

### ISSUE THREAD

**Issue by Hildepont-0** [LeMyst/WikibaseIntegrator#98]
Hi there,

following the example _A Minimal Bot for Mass Import_ on the project page, I can't add references trought `wd_item = wbi_core.ItemEngine(data=data, references=references)`

The import works but without the references : `TypeError: __init__() got an unexpected keyword argument 'references'`

**Comment by egils-consulting** [comment]
Take a look at lexutils in my repos. Util.py

**Comment by LeMyst** [comment]
Hi @Hildepont-0 
Yeah, this part seem really wrong, I'll fix this ASAP

**Comment by LeMyst** [comment]
It's pushed on master.
The references go on a BaseDataType (like ItemID or String), not directly on ItemEngine

**Comment by Hildepont-0** [comment]
thank you all,
I had just found the solution ;)

**Comment by LeMyst** [comment]
The solution from @egils-consulting ?

**Comment by egils-consulting** [comment]
@Hildepont-0 would you be willing to share you code so we can see what you use it for? I'm curious 😃

**Comment by Hildepont-0** [comment]
https://github.com/Hildepont-0/wikibase_scripts

I'm trying  to make an author database for a small library. I want to import some data (like languages, countries,...) from wikidata (sparql queries > csv > wbi). It's my first code project, I'm still experimenting at the moment...
